---
- name: user creation
  shell: './mattermost user create --email {{ item.email }} --username {{ item.name }} --password {{ password }}'
  with_items:
    - "{{ users }}"
  args:
    chdir: /opt/mattermost/bin
  ignore_errors: true
  become: yes

- name: team creation
  become: yes
  shell: './mattermost team create --name {{ item.team_name}} --display_name "{{ item.team_display_name }}"'
  with_items:
    - "{{ channels }}"
  args:
    chdir: /opt/mattermost/bin
  ignore_errors: true

- name: create channels
  shell: './mattermost channel create --team {{ item.team_name }} --name {{ item.channel_name}} --display_name "{{ item.channel_display_name }}"'
  with_items:
    - "{{ channels }}"
  args:
    chdir: /opt/mattermost/bin
  ignore_errors: true

- name: add users to teams
  shell: "./mattermost team add {{ item.team }} {{ item.email }} {{ item.name }}"
  with_items:
    - "{{ users }}"
  args:
    chdir: /opt/mattermost/bin
  ignore_errors: true

- name: add users to channel
  shell: "./mattermost channel add {{ item.team }}:{{ item.channel }} {{ item.email }} {{ item.name }}"
  with_items:
    - "{{ users }}"
  args:
    chdir: /opt/mattermost/bin
  ignore_errors: true
    
    
